#!/bin/bash
#Commiter

chmod 777 *
git add --all
git commit -m "[YOSRI- 0-binary_tree_node.c]"
git commit -m "[YOSRI- 1-binary_tree_insert_left.c]"
git commit -m "[YOSRI- 10-binary_tree_depth.c]"
git commit -m "[YOSRI- 100-binary_trees_ancestor.c]"
git commit -m "[YOSRI- 101-binary_tree_levelorder.c]"
git commit -m "[YOSRI- 103-binary_tree_rotate_left.c]"
git commit -m "[YOSRI- 104-binary_tree_rotate_right.c]"
git commit -m "[YOSRI- 11-binary_tree_size.c]"
git commit -m "[YOSRI- 12-binary_tree_leaves.c]"
git commit -m "[YOSRI- 13-binary_tree_nodes.c]"
git commit -m "[YOSRI- 14-binary_tree_balance.c]"
git commit -m "[YOSRI- 15-binary_tree_is_full.c]"
git commit -m "[YOSRI- 16-binary_tree_is_perfect.c]"
git commit -m "[YOSRI- 17-binary_tree_sibling.c]"
git commit -m "[YOSRI- 18-binary_tree_uncle.c]"
git commit -m "[YOSRI- 2-binary_tree_insert_right.c]"
git commit -m "[YOSRI- 3-binary_tree_delete.c]"
git commit -m "[YOSRI- 4-binary_tree_is_leaf.c]"
git commit -m "[YOSRI- 5-binary_tree_is_root.c]"
git commit -m "[YOSRI- 6-binary_tree_preorder.c]"
git commit -m "[YOSRI- 7-binary_tree_inorder.c]"
git commit -m "[YOSRI- 8-binary_tree_postorder.c]"
git commit -m "[YOSRI- 9-binary_tree_height.c]"
git commit -m "[YOSRI- README.md]"
git commit -m "[YOSRI- binary_tree_print.c]"
git commit -m "[YOSRI- binary_trees.h]"
git push
clear
chmod 400 *
git add --all
git commit -m "[YOSRI- 0-binary_tree_node.c]"
git commit -m "[YOSRI- 1-binary_tree_insert_left.c]"
git commit -m "[YOSRI- 10-binary_tree_depth.c]"
git commit -m "[YOSRI- 100-binary_trees_ancestor.c]"
git commit -m "[YOSRI- 101-binary_tree_levelorder.c]"
git commit -m "[YOSRI- 103-binary_tree_rotate_left.c]"
git commit -m "[YOSRI- 104-binary_tree_rotate_right.c]"
git commit -m "[YOSRI- 11-binary_tree_size.c]"
git commit -m "[YOSRI- 12-binary_tree_leaves.c]"
git commit -m "[YOSRI- 13-binary_tree_nodes.c]"
git commit -m "[YOSRI- 14-binary_tree_balance.c]"
git commit -m "[YOSRI- 15-binary_tree_is_full.c]"
git commit -m "[YOSRI- 16-binary_tree_is_perfect.c]"
git commit -m "[YOSRI- 17-binary_tree_sibling.c]"
git commit -m "[YOSRI- 18-binary_tree_uncle.c]"
git commit -m "[YOSRI- 2-binary_tree_insert_right.c]"
git commit -m "[YOSRI- 3-binary_tree_delete.c]"
git commit -m "[YOSRI- 4-binary_tree_is_leaf.c]"
git commit -m "[YOSRI- 5-binary_tree_is_root.c]"
git commit -m "[YOSRI- 6-binary_tree_preorder.c]"
git commit -m "[YOSRI- 7-binary_tree_inorder.c]"
git commit -m "[YOSRI- 8-binary_tree_postorder.c]"
git commit -m "[YOSRI- 9-binary_tree_height.c]"
git commit -m "[YOSRI- README.md]"
git commit -m "[YOSRI- binary_tree_print.c]"
git commit -m "[YOSRI- binary_trees.h]"
git push
clear
chmod 777 *
git add --all
git commit -m "[YOSRI- 0-binary_tree_node.c]"
git commit -m "[YOSRI- 1-binary_tree_insert_left.c]"
git commit -m "[YOSRI- 10-binary_tree_depth.c]"
git commit -m "[YOSRI- 100-binary_trees_ancestor.c]"
git commit -m "[YOSRI- 101-binary_tree_levelorder.c]"
git commit -m "[YOSRI- 103-binary_tree_rotate_left.c]"
git commit -m "[YOSRI- 104-binary_tree_rotate_right.c]"
git commit -m "[YOSRI- 11-binary_tree_size.c]"
git commit -m "[YOSRI- 12-binary_tree_leaves.c]"
git commit -m "[YOSRI- 13-binary_tree_nodes.c]"
git commit -m "[YOSRI- 14-binary_tree_balance.c]"
git commit -m "[YOSRI- 15-binary_tree_is_full.c]"
git commit -m "[YOSRI- 16-binary_tree_is_perfect.c]"
git commit -m "[YOSRI- 17-binary_tree_sibling.c]"
git commit -m "[YOSRI- 18-binary_tree_uncle.c]"
git commit -m "[YOSRI- 2-binary_tree_insert_right.c]"
git commit -m "[YOSRI- 3-binary_tree_delete.c]"
git commit -m "[YOSRI- 4-binary_tree_is_leaf.c]"
git commit -m "[YOSRI- 5-binary_tree_is_root.c]"
git commit -m "[YOSRI- 6-binary_tree_preorder.c]"
git commit -m "[YOSRI- 7-binary_tree_inorder.c]"
git commit -m "[YOSRI- 8-binary_tree_postorder.c]"
git commit -m "[YOSRI- 9-binary_tree_height.c]"
git commit -m "[YOSRI- README.md]"
git commit -m "[YOSRI- binary_tree_print.c]"
git commit -m "[YOSRI- binary_trees.h]"
git push
clear
chmod 400 *
git add --all
git commit -m "[YOSRI- 0-binary_tree_node.c]"
git commit -m "[YOSRI- 1-binary_tree_insert_left.c]"
git commit -m "[YOSRI- 10-binary_tree_depth.c]"
git commit -m "[YOSRI- 100-binary_trees_ancestor.c]"
git commit -m "[YOSRI- 101-binary_tree_levelorder.c]"
git commit -m "[YOSRI- 103-binary_tree_rotate_left.c]"
git commit -m "[YOSRI- 104-binary_tree_rotate_right.c]"
git commit -m "[YOSRI- 11-binary_tree_size.c]"
git commit -m "[YOSRI- 12-binary_tree_leaves.c]"
git commit -m "[YOSRI- 13-binary_tree_nodes.c]"
git commit -m "[YOSRI- 14-binary_tree_balance.c]"
git commit -m "[YOSRI- 15-binary_tree_is_full.c]"
git commit -m "[YOSRI- 16-binary_tree_is_perfect.c]"
git commit -m "[YOSRI- 17-binary_tree_sibling.c]"
git commit -m "[YOSRI- 18-binary_tree_uncle.c]"
git commit -m "[YOSRI- 2-binary_tree_insert_right.c]"
git commit -m "[YOSRI- 3-binary_tree_delete.c]"
git commit -m "[YOSRI- 4-binary_tree_is_leaf.c]"
git commit -m "[YOSRI- 5-binary_tree_is_root.c]"
git commit -m "[YOSRI- 6-binary_tree_preorder.c]"
git commit -m "[YOSRI- 7-binary_tree_inorder.c]"
git commit -m "[YOSRI- 8-binary_tree_postorder.c]"
git commit -m "[YOSRI- 9-binary_tree_height.c]"
git commit -m "[YOSRI- README.md]"
git commit -m "[YOSRI- binary_tree_print.c]"
git commit -m "[YOSRI- binary_trees.h]"
git push
clear
chmod 777 *
git add --all
git commit -m "[YOSRI- 0-binary_tree_node.c]"
git commit -m "[YOSRI- 1-binary_tree_insert_left.c]"
git commit -m "[YOSRI- 10-binary_tree_depth.c]"
git commit -m "[YOSRI- 100-binary_trees_ancestor.c]"
git commit -m "[YOSRI- 101-binary_tree_levelorder.c]"
git commit -m "[YOSRI- 103-binary_tree_rotate_left.c]"
git commit -m "[YOSRI- 104-binary_tree_rotate_right.c]"
git commit -m "[YOSRI- 11-binary_tree_size.c]"
git commit -m "[YOSRI- 12-binary_tree_leaves.c]"
git commit -m "[YOSRI- 13-binary_tree_nodes.c]"
git commit -m "[YOSRI- 14-binary_tree_balance.c]"
git commit -m "[YOSRI- 15-binary_tree_is_full.c]"
git commit -m "[YOSRI- 16-binary_tree_is_perfect.c]"
git commit -m "[YOSRI- 17-binary_tree_sibling.c]"
git commit -m "[YOSRI- 18-binary_tree_uncle.c]"
git commit -m "[YOSRI- 2-binary_tree_insert_right.c]"
git commit -m "[YOSRI- 3-binary_tree_delete.c]"
git commit -m "[YOSRI- 4-binary_tree_is_leaf.c]"
git commit -m "[YOSRI- 5-binary_tree_is_root.c]"
git commit -m "[YOSRI- 6-binary_tree_preorder.c]"
git commit -m "[YOSRI- 7-binary_tree_inorder.c]"
git commit -m "[YOSRI- 8-binary_tree_postorder.c]"
git commit -m "[YOSRI- 9-binary_tree_height.c]"
git commit -m "[YOSRI- README.md]"
git commit -m "[YOSRI- binary_tree_print.c]"
git commit -m "[YOSRI- binary_trees.h]"
git push
clear
chmod 400 *
git add --all
git commit -m "[YOSRI- 0-binary_tree_node.c]"
git commit -m "[YOSRI- 1-binary_tree_insert_left.c]"
git commit -m "[YOSRI- 10-binary_tree_depth.c]"
git commit -m "[YOSRI- 100-binary_trees_ancestor.c]"
git commit -m "[YOSRI- 101-binary_tree_levelorder.c]"
git commit -m "[YOSRI- 103-binary_tree_rotate_left.c]"
git commit -m "[YOSRI- 104-binary_tree_rotate_right.c]"
git commit -m "[YOSRI- 11-binary_tree_size.c]"
git commit -m "[YOSRI- 12-binary_tree_leaves.c]"
git commit -m "[YOSRI- 13-binary_tree_nodes.c]"
git commit -m "[YOSRI- 14-binary_tree_balance.c]"
git commit -m "[YOSRI- 15-binary_tree_is_full.c]"
git commit -m "[YOSRI- 16-binary_tree_is_perfect.c]"
git commit -m "[YOSRI- 17-binary_tree_sibling.c]"
git commit -m "[YOSRI- 18-binary_tree_uncle.c]"
git commit -m "[YOSRI- 2-binary_tree_insert_right.c]"
git commit -m "[YOSRI- 3-binary_tree_delete.c]"
git commit -m "[YOSRI- 4-binary_tree_is_leaf.c]"
git commit -m "[YOSRI- 5-binary_tree_is_root.c]"
git commit -m "[YOSRI- 6-binary_tree_preorder.c]"
git commit -m "[YOSRI- 7-binary_tree_inorder.c]"
git commit -m "[YOSRI- 8-binary_tree_postorder.c]"
git commit -m "[YOSRI- 9-binary_tree_height.c]"
git commit -m "[YOSRI- README.md]"
git commit -m "[YOSRI- binary_tree_print.c]"
git commit -m "[YOSRI- binary_trees.h]"
git push
clear
chmod 777 *
git add --all
git commit -m "[YOSRI- 0-binary_tree_node.c]"
git commit -m "[YOSRI- 1-binary_tree_insert_left.c]"
git commit -m "[YOSRI- 10-binary_tree_depth.c]"
git commit -m "[YOSRI- 100-binary_trees_ancestor.c]"
git commit -m "[YOSRI- 101-binary_tree_levelorder.c]"
git commit -m "[YOSRI- 103-binary_tree_rotate_left.c]"
git commit -m "[YOSRI- 104-binary_tree_rotate_right.c]"
git commit -m "[YOSRI- 11-binary_tree_size.c]"
git commit -m "[YOSRI- 12-binary_tree_leaves.c]"
git commit -m "[YOSRI- 13-binary_tree_nodes.c]"
git commit -m "[YOSRI- 14-binary_tree_balance.c]"
git commit -m "[YOSRI- 15-binary_tree_is_full.c]"
git commit -m "[YOSRI- 16-binary_tree_is_perfect.c]"
git commit -m "[YOSRI- 17-binary_tree_sibling.c]"
git commit -m "[YOSRI- 18-binary_tree_uncle.c]"
git commit -m "[YOSRI- 2-binary_tree_insert_right.c]"
git commit -m "[YOSRI- 3-binary_tree_delete.c]"
git commit -m "[YOSRI- 4-binary_tree_is_leaf.c]"
git commit -m "[YOSRI- 5-binary_tree_is_root.c]"
git commit -m "[YOSRI- 6-binary_tree_preorder.c]"
git commit -m "[YOSRI- 7-binary_tree_inorder.c]"
git commit -m "[YOSRI- 8-binary_tree_postorder.c]"
git commit -m "[YOSRI- 9-binary_tree_height.c]"
git commit -m "[YOSRI- README.md]"
git commit -m "[YOSRI- binary_tree_print.c]"
git commit -m "[YOSRI- binary_trees.h]"
git push
clear
echo "\n\n\t>> Done for 175 Commit\n\n"